
package tutorial8client;

import tutorial8client.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Tutorial8WebService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/Tutorial8WebApplication/Tutorial8WebService?wsdl")
public class Tutorial8WebService_Service
    extends Service
{

    private final static URL TUTORIAL8WEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TUTORIAL8WEBSERVICE_EXCEPTION;
    private final static QName TUTORIAL8WEBSERVICE_QNAME = new QName("http://server/", "Tutorial8WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Tutorial8WebApplication/Tutorial8WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TUTORIAL8WEBSERVICE_WSDL_LOCATION = url;
        TUTORIAL8WEBSERVICE_EXCEPTION = e;
    }

    public Tutorial8WebService_Service() {
        super(__getWsdlLocation(), TUTORIAL8WEBSERVICE_QNAME);
    }

    public Tutorial8WebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TUTORIAL8WEBSERVICE_QNAME, features);
    }

    public Tutorial8WebService_Service(URL wsdlLocation) {
        super(wsdlLocation, TUTORIAL8WEBSERVICE_QNAME);
    }

    public Tutorial8WebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TUTORIAL8WEBSERVICE_QNAME, features);
    }

    public Tutorial8WebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Tutorial8WebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tutorial8WebService
     */
    @WebEndpoint(name = "Tutorial8WebServicePort")
    public Tutorial8WebService getTutorial8WebServicePort() {
        return super.getPort(new QName("http://server/", "Tutorial8WebServicePort"), Tutorial8WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tutorial8WebService
     */
    @WebEndpoint(name = "Tutorial8WebServicePort")
    public Tutorial8WebService getTutorial8WebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "Tutorial8WebServicePort"), Tutorial8WebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TUTORIAL8WEBSERVICE_EXCEPTION!= null) {
            throw TUTORIAL8WEBSERVICE_EXCEPTION;
        }
        return TUTORIAL8WEBSERVICE_WSDL_LOCATION;
    }

}
